[trail]
enabled = true
color = [255, 255, 255, 255]
max_length = 300.0
width = 5.0
taper = 1.0
kill_time = 0.10

[avatar]
enabled = true
# image_path = "assets/avatar.png"
string_length = 90.0
string_slack = 0.40
size = 25.0
gravity = 900.0
damping = 0.15
string_color = [220, 220, 220, 220]
string_width = 1.0

[window]
fps = 60
hide_after_idle_secs = 3.0
